version: build.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
before_build:
- ps: >-
    nuget restore


    [xml]$proj = Get-Content src/StringToExpression/StringToExpression.csproj

    $semver = $proj.Project.PropertyGroup.Version

    Set-AppveyorBuildVariable "semver" $semver

    Update-AppveyorBuild -Version "$semver-build.${env:APPVEYOR_BUILD_NUMBER}"
build:
  verbosity: minimal
artifacts:
- path: src\StringToExpression\bin\Release\StringToExpression.*.*.*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: NTqy7aQ741jkqBIbCZYWh9r6hRV0JbDw9xzDukvhcW7f4WEuWFEOK4S7scwElnI4
  on:
    branch: master
- provider: GitHub
  release: v$(semver)
  auth_token:
    secure: YywQETyUzGaUkJglZ0PZtDz/Jf+uZKhpXHvV0Ktia2FqW4FTSPQZ1MLn4kcM+tsq
  artifact: nupkg
  on:
    branch: master
